package com.appstack.reactnative

import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReadableMap
import com.facebook.react.module.annotations.ReactModule

/**
 * New-architecture module. Compiled only when newArchEnabled is true
 * (see the sourceSets block in android/build.gradle).
 *
 * NativeAppstackReactNativeSpec is generated by codegen into this same package
 * (codegenConfig.android.javaPackageName), so it needs no import. It must remain
 * the DIRECT superclass: JavaModuleWrapper only walks one level up when locating
 * the spec's @ReactMethod declarations, so inserting an intermediate class would
 * silently break the legacy bridge interop path.
 *
 * No @ReactMethod annotations here — the generated abstract methods already carry
 * them, and real TurboModule dispatch uses the C++ methodMap_ built from the schema.
 */
@ReactModule(name = AppstackReactNativeModuleImpl.NAME)
class AppstackReactNativeModule(reactContext: ReactApplicationContext) :
    NativeAppstackReactNativeSpec(reactContext) {

    private val impl = AppstackReactNativeModuleImpl(reactContext)

    // getName() is provided by the generated spec and returns NAME.

    override fun configure(apiKey: String, logLevel: Double, customerUserId: String?, promise: Promise) {
        impl.configure(apiKey, logLevel, customerUserId, promise)
    }

    override fun setCustomerUserId(customerUserId: String?, promise: Promise) {
        impl.setCustomerUserId(customerUserId, promise)
    }

    override fun sendEvent(eventType: String?, eventName: String?, parameters: ReadableMap?, promise: Promise) {
        impl.sendEvent(eventType, eventName, parameters, promise)
    }

    override fun enableAppleAdsAttribution(promise: Promise) {
        impl.enableAppleAdsAttribution(promise)
    }

    override fun disableASAAttributionTracking(promise: Promise) {
        impl.disableASAAttributionTracking(promise)
    }

    override fun clearData(promise: Promise) {
        impl.clearData(promise)
    }

    override fun isEnabled(promise: Promise) {
        impl.isEnabled(promise)
    }

    override fun getAppstackId(promise: Promise) {
        impl.getAppstackId(promise)
    }

    override fun isSdkDisabled(promise: Promise) {
        impl.isSdkDisabled(promise)
    }

    override fun getAttributionParams(promise: Promise) {
        impl.getAttributionParams(promise)
    }
}
